- name: install cron job (ping-logging)
  cron:
    user: vagrant
    name: "ping-logging"
    minute: "*/1"
    job: "ping -c 3 10.0.0.21 | while read pong; do echo \"$(date): $pong\"; done > /var/log/ping.log"